### PR TITLE
Added support for relational operators in prepared statement queries

### PR DESCRIPTION
**Pull request by levinson**
* Added support for relational operators (less than, less than or equal, greater than, greater than or equal) in prepared statement queries.
* Added new tests for prepared statement queries with relational operators using new test table 'Clicks'.

### CODE REVIEW

**Comment by alexflav23** [comment]
Hi @levinson,

This one is on me. You can ignore the failing test in `DatabaseImplTest` none of the last 2 tests should work yet. If you `git commit --amend` and `git push -f` that should fix the build and we can merge.

Many thanks once again!

Regards.

**Comment by levinson** [comment]
Hi @alexflav23,

I have done as you suggested, and also rebased against the updated develop branch, but it appears that some tests are still failing on Travis CI. Let me know if I can help, or if you would like to see any other changes in my pull request.

Thanks!

**Comment by alexflav23** [comment]
Hi @levinson,

I fixed the remaining errors locally on a copy of your branch. You forgot to initialise the schema in Cassandra using table auto-creation, phantom has a helper method inside tests which you can call inside `beforeAll`, namely `table.insertSchema`, which is just a 10 second blocking await on the table creation future.

You then mixed in the `clicks` table in a `TestDatabase` that was meant to be used only for assertions against more esoteric reflection properties we rely on. There was a different class in use to do actual CRUD testing, and when adding another table to that database you made a test fail as it had an assertion for the number of tables inside the database.

**Comment by alexflav23** [comment]
Hi @levinson,

I have already merged your PR in from a custom branch. A release will be done today and you will have all the new additions available. Once again many thanks for taking the time to contribute!

Regards.

**Pull request closed without merging**
