### PR TITLE
Added support for relational operators in prepared statements

### PR DESCRIPTION
**Pull request by levinson**
* Added support for relational operators (less than, less than or equal, greater than, greater than or equal) in prepared statements. Added new tests for prepared statement relational operators using new column 'calories' added to the Recipes table.
* Added test for prepared statements using less than and greater than with new column 'calories' added to the 'recipes' table.

### CODE REVIEW

**Comment by alexflav23** [comment]
Hi @levinson,

A few things:

- Tests are failing as you are using an incorrect CQL query, hopefully that's not the result of another bug.
- It wouldn't be possible to merge this. CRUD tests should not address operators in prepared queries, please create a new test class inside the `prepared` package where all the rest of prepared query tests are defined, to make it easier to manage everything.

Otherwise many thanks for your contribution, we look forward to getting it merged!

**Comment by levinson** [comment]
I have updated this PR with new test for file for relational operators and added several more tests. As for the 'incorrect CQL' I think the problem is that the recipes table is persisted to the database (across multiple test executions), and it needs to be dropped to allow the schema to be updated with the new 'calories' column. The new tests all work fine for me locally.

**Comment by alexflav23** [comment]
Hi @levinson ,

You still haven't fixed the issues I mentioned earlier with the test structure. There also needs to be a new table for all these tests. Please let me know if you need further help before we can get this merged in.

Regards.

**Comment by levinson** [comment]
@alexflav23 -- I had moved the test to a new file and added several more tests. What other issues are there with the test structure? I will add a new table, update the tests and prepare a new pull request.

**Comment by alexflav23** [comment]
Hi @levinson ,

That's all I can think of, if you change all that it should be perfect. Many thanks!

**Pull request closed without merging**
