### PR TITLE
New JDK8 module with support of java.time columns

### PR DESCRIPTION
**Pull request by mmatloka**

### CODE REVIEW

**Comment by alexflav23** [comment]
Hi @mmatloka,

This is a bit of a bad thing, as phantom is JDK7 compatible and we have no plans of breaking that. Adding a new module just for these 4 columns may again be a tiny bit of overkill, we are working to find the best compromise here.

As always, your contributions remain most appreciated, but given phantom is a worldwide standard I don't want to rush a merge which will result in 10k downloads of an incompatible module and inboxes flooded with support tickets.

Regards.

**Comment by mmatloka** [comment]
Hi @alexflav23,

I am aware that phantom is JDK7 compatible, so a separate module for JDK8 related features looks like a best solution, so that it is "optional" for phantom users. JDK8 is already a while out there, JDK7 is even depracated, and I would consider support of `java.time` as worthy feature. I also remember that in the past someone else already asked for support of these classes.

**Comment by alexflav23** [comment]
Hi @mmatloka,

I wonder if we can make tests account for the JDK version somehow. I know it can be done in the build config of Travis, but there may be a way within the tests themselves.

Regards.

**Comment by mmatloka** [comment]
Probably it would be needed to disable building of given module when jdk7 is used. Otherwise disabling tests won't be enough since it will just not compile udner jdk7 because there are no `java.time` classes in it.

**Comment by alexflav23** [comment]
Hi @mmatloka.

Hmm you may be right indeed, I think I'm becoming prematurely senile to miss the obvious. I will look at a way of doing this in TravisCI, still not entire sure how.

Regards.

**Comment by mmatloka** [comment]
Rebased against develop, added `ZonedDateTime` related columns and added conditional build for this module on sbt level so it works for jdk7 on travis :).

**Comment by alexflav23** [comment]
Hi @mmatloka,

Apologies for the late reply, I've merged this into a new PR and merged in all the new releases, resolved conflicts and the works. It will go in today, as always many thanks for taking the time to contribute.

Regards.

**Pull request closed without merging**
